---
- name: top 5 high cpu usage
  hosts: webservers
  tasks: 
        - name: Get CPU usage 
          shell: "top -b -n 1 | head -n 5" 
          register: top 
 
        - name: Set CPU usage facts 
          set_fact: 
                        user_cpu: "{{top.stdout_lines[2].split()[1]}}" 
                        system_cpu: "{{top.stdout_lines[2].split()[3]}}" 
 
        - name: Output CPU usage facts 
          debug: 
                        msg: 
                          - "User CPU usage: {{user_cpu}}" 
                          - "System CPU usage: {{system_cpu}}"
