---
- name: checking service is running or not
  hosts: webservers
  connection: local
  become: true

  tasks:
  - name: get service facts
    service_facts:

  - name: access the service
    debug:
      var:
          ansible_facts.services["httpd.service"]

