---
- hosts: webservers
  tasks:
        - name: get service facts
        service_facts:
        - name: access the service
          debug:
             var:
                ansible_facts.services["httpd.service"]
